# This template is a reusable set of steps that can be shared by multiple CI pipelines.
#
# Documentation for this file format is here:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

steps:
    - script: 'git config --local user.email dpreleasebot@hbo.com'
      displayName: 'git config email'

    - script: 'git config --local user.name hbo-github-bot'
      displayName: 'git config name'

    - script: 'npm ci'
      displayName: 'Install: wiremock-captain'

    - script: 'npm run build'
      displayName: 'Build: wiremock-captain'

    - script: 'npm run coverage'
      displayName: 'Unit Test: wiremock-captain'

    - script: 'make integration-test'
      displayName: 'Integration Test: wiremock-captain'

    - script: 'npm install'
      displayName: 'Install: express-app demo project'
      workingDirectory: examples/express-app

    - script: 'npm run build'
      displayName: 'Build: express-app demo project'
      workingDirectory: examples/express-app
