# This is a basic workflow to help you get started with Actions

name: changelog

# Controls when the workflow will run
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Tag Changelog
        # You may pin to the exact commit or the version.
        # uses: loopwerk/tag-changelog@6730d9b2742044f6cedff39324e8179f5867c6d4
        uses: loopwerk/tag-changelog@v1.0.4
        with:
          # Github repository token
          token: ${{ secrets.GITHUB_TOKEN }}
