name: PR title check
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

permissions: read-all

jobs:
  check_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR Title Verify
        uses: satvik-s/pr-title-check@1.1.0
        with:
          pattern: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)'
